/**
 * Emits a runnable DeepTrack2 script reproducing the current experiment.
 *
 * This is the strategic half of the module: the browser removes the barrier to
 * entry, and the export makes sure it is not also the ceiling. The script must
 * run unmodified against a current `deeptrack`, so the API used here was
 * checked against the installed package rather than taken on trust:
 *
 *  - `Fluorescence(NA, wavelength, resolution, magnification,
 *     refractive_index_medium, output_region, upscale)` — verified signature.
 *  - `PointParticle(position=..., intensity=...)`, `^` to replicate,
 *    `dt.Sequence(..., sequence_length=...)`.
 *  - The sequential-property API differs across releases: deeptrack 2.0.1 (PyPI)
 *    has only the deprecated `dt.Sequential(feature, position=...)`, while the
 *    development branch replaces it with `feature.to_sequential(...)`. The brief
 *    assumed the latter, which raises AttributeError on the released package, so
 *    the script picks whichever exists.
 *  - `dt.Poisson(snr=...)` exists but is NOT a photon-count model: it rescales
 *    the image so the peak above background matches a target SNR, then samples.
 *    This module works in physical photons, so the script applies shot noise and
 *    read noise explicitly with numpy, and normalises DeepTrack's arbitrary
 *    intensity scale to a photon budget first (DeepTrack's `intensity` is not a
 *    photon count — a unit-intensity emitter integrates to ~0.095, not 1).
 *
 * The optics — the part being cross-checked — stays DeepTrack's.
 */
import type { Values } from './compute';

export interface ExportOptions {
  /** Permalink reproducing this exact state in the browser. */
  permalink: string;
  version: string;
}

/** Number formatting that always yields a valid Python literal. */
function py(v: number): string {
  if (!Number.isFinite(v)) return 'float("nan")';
  return Number.isInteger(v) ? String(v) : String(Number(v.toPrecision(12)));
}

/** Immersion index implied by the NA, so the emitted script stays physical. */
export function mediumIndexFor(NA: number): number {
  if (NA > 1.35) return 1.518; // oil
  if (NA > 1.0) return 1.33; // water
  return 1.0; // dry
}

export function toPythonScript(p: Values, opt: ExportOptions): string {
  const N = Number(p.N);
  const D = Number(p.D);
  const dtMs = Number(p.dt);
  const pixel = Number(p.pixel);
  const NA = Number(p.NA);
  const lambda = Number(p.lambda);
  const field = Number(p.field);
  const photons = Number(p.photons);
  const background = Number(p.background);
  const readNoise = Number(p.readNoise);
  const frames = Number(p.frames);
  const seed = Number(p.seed);
  const qe = p.qe === undefined ? 1 : Number(p.qe);
  const nMedium = mediumIndexFor(NA);

  return `# Generated by NanophotonicsLab — Imaging / Diffusion and Tracking (IMG1) v${opt.version}
# Permalink: ${opt.permalink}
#
# Reproduces the browser run in DeepTrack2. The optics are DeepTrack's; the
# detector chain is applied explicitly in photon units, because dt.Poisson
# targets a signal-to-noise ratio rather than a photon count (see below).
#
#   pip install deeptrack
import numpy as np
import deeptrack as dt

# ── parameters ───────────────────────────────────────────────────────────────
N        = ${py(N)}            # particles
D        = ${py(D)}            # um^2/s
DT       = ${py(dtMs / 1000)}  # s (frame interval)
PIXEL    = ${py(pixel)}        # nm at the sample
NA       = ${py(NA)}
LAMBDA   = ${py(lambda)}       # nm (emission)
N_MEDIUM = ${py(nMedium)}      # immersion index implied by the NA
FIELD    = ${py(field)}        # px
PHOTONS  = ${py(photons)}      # photons per particle per frame
BACKGND  = ${py(background)}   # photons per pixel per frame
READNOISE= ${py(readNoise)}    # electrons rms
QE       = ${py(qe)}
FRAMES   = ${py(frames)}
SEED     = ${py(seed)}

rng = np.random.default_rng(SEED)

# per-axis Brownian step, in pixels
sigma_step_px = np.sqrt(2 * D * DT) * 1000 / PIXEL

def update_position(previous_value):
    """One Brownian step, wrapped periodically into the field of view."""
    return (previous_value + rng.normal(0, sigma_step_px, 2)) % FIELD

particle = dt.PointParticle(
    position=lambda: rng.uniform(0, FIELD, 2),
    intensity=1.0,               # arbitrary units; renormalised to photons below
)

# The sequential-property API moved between releases: 2.0.1 ships the deprecated
# dt.Sequential(), the development branch ships Feature.to_sequential().
if hasattr(particle, "to_sequential"):
    walker = particle.to_sequential(position=update_position)
else:
    walker = dt.Sequential(particle, position=update_position)

optics = dt.Fluorescence(
    NA=NA,
    wavelength=LAMBDA * 1e-9,
    resolution=PIXEL * 1e-9,
    magnification=1,
    refractive_index_medium=N_MEDIUM,
    output_region=(0, 0, FIELD, FIELD),
    # Note on PSF width: DeepTrack samples the pupil on the output grid, and at
    # this pixel size that disc is only ~10 samples in radius, so its pixelated
    # edge widens the PSF by a few percent. Raising \`upscale\` converges it, but
    # upscale > 1 combined with dt.Sequence overflows DeepTrack's FFT size table,
    # so the default is kept here. The browser module's own PSF is the Gaussian
    # approximation sigma = 0.21 lambda / NA, about 4% narrower than an ideal
    # Airy pattern; see the module's validation note.
)

pipeline = optics(walker ^ N)
movie = dt.Sequence(pipeline, sequence_length=FRAMES)

# ── photon normalisation ─────────────────────────────────────────────────────
# DeepTrack's \`intensity\` is not a photon count: a unit-intensity emitter
# integrates to ~0.095 here, and the constant depends on NA, wavelength and
# pixel size. Calibrate it once on a single centred emitter so that each
# particle really does emit PHOTONS photons per frame.
_calib_particle = dt.PointParticle(
    position=(FIELD / 2 + 0.5, FIELD / 2 + 0.5), intensity=1.0,
)
_calib = np.asarray(optics(_calib_particle)()).astype(float)
if _calib.ndim == 3:
    _calib = _calib[..., 0]
PHOTON_SCALE = PHOTONS / _calib.sum()

# ── run ──────────────────────────────────────────────────────────────────────
frames = movie.update()()
frames = [np.asarray(f).astype(float) for f in frames]
frames = [f[..., 0] if f.ndim == 3 else f for f in frames]

electrons = []
for signal in frames:
    photons = signal * PHOTON_SCALE + BACKGND
    # shot noise on the detected photoelectrons, then Gaussian read noise
    e = rng.poisson(np.clip(photons * QE, 0, None)).astype(float)
    if READNOISE > 0:
        e += rng.normal(0, READNOISE, e.shape)
    electrons.append(e)
movie_e = np.stack(electrons)          # (FRAMES, FIELD, FIELD), photoelectrons

print("movie:", movie_e.shape, "mean", movie_e.mean().round(2))

# An equivalent using DeepTrack's own noise convention, for comparison — note it
# fixes a target SNR instead of a photon budget, so absolute counts differ:
#   pipeline = optics(walker ^ N) >> dt.Background(offset=BACKGND) \\
#              >> dt.Poisson(snr=${py(Math.max(1, Math.round(Math.sqrt(photons))))}, background=BACKGND)

# ── quick look ───────────────────────────────────────────────────────────────
try:
    import matplotlib.pyplot as plt
    plt.imshow(movie_e[0], cmap="gray")
    plt.title("frame 0 — photoelectrons")
    plt.colorbar()
    plt.show()
except ImportError:
    pass
`;
}

/** Ground-truth CSV: exact positions, because they are an input, not a fit. */
export function groundTruthCsv(
  truth: { x: Float64Array; y: Float64Array; N: number; frames: number },
  pixelNm: number, photons: number,
): string {
  const rows = ['frame,particle_id,x_nm,y_nm,x_px,y_px,photons'];
  for (let t = 0; t < truth.frames; t++) {
    for (let i = 0; i < truth.N; i++) {
      const x = truth.x[t * truth.N + i];
      const y = truth.y[t * truth.N + i];
      rows.push(
        `${t},${i},${x.toFixed(3)},${y.toFixed(3)},`
        + `${(x / pixelNm).toFixed(4)},${(y / pixelNm).toFixed(4)},${photons}`,
      );
    }
  }
  return rows.join('\n');
}

/** Localized detections, with the linked track id where one was assigned. */
export function tracksCsv(
  tracks: { id: number; points: { frame: number; xPx: number; yPx: number }[] }[],
  pixelNm: number,
): string {
  const rows = ['frame,track_id,x_nm,y_nm,x_px,y_px'];
  const flat: { frame: number; id: number; xPx: number; yPx: number }[] = [];
  for (const tr of tracks) {
    for (const q of tr.points) flat.push({ frame: q.frame, id: tr.id, xPx: q.xPx, yPx: q.yPx });
  }
  flat.sort((a, b) => a.frame - b.frame || a.id - b.id);
  for (const r of flat) {
    rows.push(
      `${r.frame},${r.id},${(r.xPx * pixelNm).toFixed(3)},${(r.yPx * pixelNm).toFixed(3)},`
      + `${r.xPx.toFixed(4)},${r.yPx.toFixed(4)}`,
    );
  }
  return rows.join('\n');
}
